title: Political Science and Diplomacy
tagline: 40. PAGE
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://INCHANI.github.io/PSD

aux_links:
  Template Repository: https://github.com/INCHANI.github.io/PSD
